<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('leagues', function (Blueprint $table): void { $table->id(); $table->string('external_id')->unique(); $table->string('name'); $table->string('country', 3); $table->string('tier', 20)->default('standard'); $table->unsignedSmallInteger('club_count')->default(20); $table->boolean('is_premium')->default(false); $table->string('logo_url')->nullable(); $table->timestamps(); });
        Schema::create('seasons', function (Blueprint $table): void { $table->id(); $table->foreignId('league_id')->constrained()->cascadeOnDelete(); $table->string('external_id')->unique(); $table->string('name'); $table->date('starts_at'); $table->date('ends_at'); $table->string('status', 20)->default('active')->index(); $table->timestamps(); });
        Schema::create('league_teams', function (Blueprint $table): void { $table->foreignId('league_id')->constrained()->cascadeOnDelete(); $table->foreignId('team_id')->constrained()->cascadeOnDelete(); $table->foreignId('season_id')->constrained()->cascadeOnDelete(); $table->unsignedSmallInteger('position')->nullable(); $table->unsignedSmallInteger('points')->default(0); $table->primary(['league_id', 'team_id', 'season_id']); });
        Schema::create('matches', function (Blueprint $table): void { $table->id(); $table->foreignId('season_id')->constrained()->cascadeOnDelete(); $table->string('external_id')->unique(); $table->foreignId('home_team_id')->constrained('teams')->cascadeOnDelete(); $table->foreignId('away_team_id')->constrained('teams')->cascadeOnDelete(); $table->timestamp('kickoff_at')->nullable()->index(); $table->string('status', 20)->default('scheduled'); $table->unsignedSmallInteger('home_score')->nullable(); $table->unsignedSmallInteger('away_score')->nullable(); $table->jsonb('events')->nullable(); $table->timestamps(); });
        Schema::create('lineups', function (Blueprint $table): void { $table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('match_id')->constrained()->cascadeOnDelete(); $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->string('formation', 12); $table->string('tactic', 30)->default('balanced'); $table->jsonb('settings')->nullable(); $table->timestamps(); $table->unique(['user_id', 'match_id']); });
        Schema::create('lineup_players', function (Blueprint $table): void { $table->foreignId('lineup_id')->constrained()->cascadeOnDelete(); $table->foreignId('player_id')->constrained()->cascadeOnDelete(); $table->string('position', 8); $table->string('role', 20)->nullable(); $table->primary(['lineup_id', 'player_id']); });
        Schema::create('stadiums', function (Blueprint $table): void { $table->id(); $table->string('external_id')->unique()->nullable(); $table->string('name'); $table->unsignedInteger('capacity'); $table->unsignedSmallInteger('level')->default(1); $table->decimal('revenue_multiplier', 6, 3)->default(1); $table->jsonb('visual')->nullable(); $table->timestamps(); });
        Schema::create('team_stadiums', function (Blueprint $table): void { $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->foreignId('stadium_id')->constrained()->cascadeOnDelete(); $table->boolean('is_primary')->default(true); $table->timestamps(); $table->unique(['team_id', 'stadium_id']); });
        Schema::create('stadium_upgrades', function (Blueprint $table): void { $table->id(); $table->foreignId('stadium_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('category', 30); $table->unsignedSmallInteger('level')->default(1); $table->unsignedSmallInteger('max_level')->default(10); $table->unsignedBigInteger('price_cents'); $table->jsonb('effects')->nullable(); $table->timestamps(); });
        Schema::create('power_types', function (Blueprint $table): void { $table->id(); $table->string('key')->unique(); $table->string('name'); $table->string('element', 20); $table->string('description'); $table->unsignedSmallInteger('default_bonus')->default(0); $table->timestamps(); });
        Schema::table('items', function (Blueprint $table): void { $table->foreignId('power_type_id')->nullable()->after('id')->constrained()->nullOnDelete(); $table->unsignedSmallInteger('max_durability')->default(100)->after('power'); });
        Schema::create('player_inventory', function (Blueprint $table): void { $table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('item_id')->constrained()->cascadeOnDelete(); $table->foreignId('equipped_player_id')->nullable()->constrained('players')->nullOnDelete(); $table->unsignedSmallInteger('quantity')->default(1); $table->unsignedSmallInteger('durability')->default(100); $table->timestamps(); $table->index(['user_id', 'equipped_player_id']); });
        Schema::create('sync_runs', function (Blueprint $table): void { $table->id(); $table->string('resource', 30); $table->string('status', 20)->index(); $table->unsignedInteger('records_processed')->default(0); $table->timestamp('started_at'); $table->timestamp('finished_at')->nullable(); $table->text('error_message')->nullable(); $table->string('provider_cursor')->nullable(); $table->timestamps(); });
    }
    public function down(): void { Schema::dropIfExists('sync_runs'); Schema::dropIfExists('player_inventory'); Schema::table('items', fn (Blueprint $table) => $table->dropConstrainedForeignId('power_type_id')); Schema::dropIfExists('power_types'); Schema::dropIfExists('stadium_upgrades'); Schema::dropIfExists('team_stadiums'); Schema::dropIfExists('stadiums'); Schema::dropIfExists('lineup_players'); Schema::dropIfExists('lineups'); Schema::dropIfExists('matches'); Schema::dropIfExists('league_teams'); Schema::dropIfExists('seasons'); Schema::dropIfExists('leagues'); }
};
